In [1]:
import pandas

In [2]:
df = pandas.read_csv('/home/adrian/projects/scGBM/older_runs/adj.csv', index_col=False)
print(df.shape)
df.head(25)

(4923325, 3)

       TF  target  importance
0   RPS4X   RPL30  218.955724
1   RPS4X   RPS12  216.259794
2   RPS4X    RPS8  207.446324
3   RPS4X  RPS15A  203.577049
4   RPS4X   RPS23  203.487693
5   RPS4X   RPL32  203.170801
6   RPS4X   RPS3A  199.582556
7   RPS4X   RPL13  196.324096
8   KLRG1    GZMK  193.160273
9   RPS4X   RPL19  192.680016
10  RPS4X    RPS6  192.274365
11  RPS4X   RPS16  191.522052
12  TBX21    NKG7  190.068623
13  RPS4X   RPS18  187.002166
14  RPS4X   RPLP2  184.839241
15  RPS4X    RPL9  184.514496
16  RPS4X   RPL18  183.518339
17  RPS4X   RPL36  183.218429
18  RPS4X    RPS5  182.495580
19  RPS4X   RPL34  180.206565
20  RPS4X  RPS27A  179.757489
21  RPS4X    RPS3  178.607052
22  RPS4X    RPL3  177.923207
23  RPS4X   RPLP1  176.958825
24  RPS4X  RPL35A  176.339817

In [3]:
df = pandas.read_csv('/home/adrian/projects/scGBM/older_runs/adj_9workers.tsv', index_col=False, sep='\t')
print(df.shape)
df.head(25)

(4926892, 3)

       TF  target  importance
0   RPS4X   RPS12  224.376914
1   RPS4X   RPS3A  224.121428
2   RPS4X   RPL30  212.436273
3   RPS4X   RPS23  202.623816
4   RPS4X   RPL39  200.921529
5   RPS4X   RPS14  187.883354
6   RPS4X   RPS28  187.791842
7   RPS4X  RPL35A  187.687936
8   RPS4X   RPL34  187.081826
9   TBX21   KLRD1  186.136620
10  RPS4X   RPL32  185.179250
11  RPS4X   RPL11  184.197555
12   FOSB     JUN  183.588351
13  RPS4X    RPS3  182.811045
14  RPS4X  RPS15A  182.735633
15  RPS4X   RPL13  182.395500
16  RPS4X    RPS6  182.067709
17  RPS4X    RPL9  181.435929
18  RPS4X   RPS18  180.946331
19  RPS4X    RPL3  180.943763
20  RPS4X   RPS27  177.444661
21  RPS4X   RPL18  176.649061
22  RPS4X   RPL29  176.142585
23  RPS4X  RPL23A  175.249876
24  TBX21    NKG7  173.867149